[project]
name = "explorable"
version = "0.1.0"
description = "A place for concepts and ideas I'm interested in."
authors = [
    {name = "Theo-BRN",email = "theobrn@live.co.uk"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "marimo (>=0.24.2,<0.25.0)",
    "numpy (>=2.5.3,<3.0.0)",
    "pandas (>=3.0.6,<4.0.0)",
    "matplotlib (>=3.11.2,<4.0.0)",
    "plotly (>=7.1.0,<8.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
